export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR"
export const PRODUCTS_FETCH_BEGIN = "PRODUCTS_LOADING_BEGIN"
export const PRODUCTS_FETCH_SUCCESS = "PRODUCTS_FETCH_SUCCESS"
export const PRODUCTS_FETCH_ERROR = "PRODUCTS_FETCH_ERROR"
